version: '3'
services:
  your-application:
    image: your-application-name
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - database

  database:
    image: postgres:12
    environment:
      - POSTGRES_DB=your-database-name #For example
      - POSTGRES_USER=your-database-user #For example
      - POSTGRES_PASSWORD=your-database-password #For example